name: Java CI avec Maven

on:
  workflow_dispatch:  # Permet de lancer le workflow manuellement
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compiler avec Maven
        run: mvn compile

      - name: Lancer les tests
        run: mvn test
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=5b47eea90f672ea72952b1f54ed5df676b4d78f5 -Dsonar.host.url=https://sonarcloud.io/